import type { GoldItem } from "@/rag/types";

export const goldSet: GoldItem[] = [
  {
    id: "q01",
    question: "قطعه‌بندی خیلی بزرگ چه مشکلی در RAG ایجاد می‌کند؟",
    language: "fa",
    kind: "factual",
    goldAnswer: "نویز وارد زمینه می‌کند و گم‌شدن در میانه را بدتر می‌کند.",
    relevantDocIds: ["chunking", "lost-middle"],
  },
  {
    id: "q02",
    question: "چرا برای قطعه‌ها شناسهٔ پایدار لازم است؟",
    language: "fa",
    kind: "factual",
    goldAnswer: "بدون شناسه نمی‌توان Recall@k و استناد را اندازه گرفت.",
    relevantDocIds: ["chunking", "citations"],
  },
  {
    id: "q03",
    question: "هم‌پوشانی در chunking معمولاً چه کمکی می‌کند؟",
    language: "fa",
    kind: "factual",
    goldAnswer: "جلوگیری از از دست رفتن جمله‌ای که روی مرز قطعه می‌افتد.",
    relevantDocIds: ["chunking"],
  },
  {
    id: "q04",
    question: "نقطه قوت BM25 در بازیابی چیست؟",
    language: "fa",
    kind: "factual",
    goldAnswer: "تطبیق دقیق اصطلاحات نادر مثل نام متریک یا شناسه API.",
    relevantDocIds: ["bm25"],
  },
  {
    id: "q05",
    question: "ضعف اصلی BM25 کجاست؟",
    language: "fa",
    kind: "factual",
    goldAnswer: "ترادف و بازنویسی؛ اگر واژه‌ها یکی نباشند ممکن است امتیاز صفر بگیرد.",
    relevantDocIds: ["bm25", "dense"],
  },
  {
    id: "q06",
    question: "Why should Recall@10 not be the only retrieval metric when the generator sees 4 chunks?",
    language: "en",
    kind: "factual",
    goldAnswer: "The metric must match the k actually passed to the generator.",
    relevantDocIds: ["bm25", "ir-metrics"],
  },
  {
    id: "q07",
    question: "بازیابی متراکم چه چیزی را بهتر از BM25 می‌گیرد؟",
    language: "fa",
    kind: "comparison",
    goldAnswer: "ترادف و بازنویسی معنایی مثل کاهش توهم در برابر groundedness.",
    relevantDocIds: ["dense", "bm25"],
  },
  {
    id: "q08",
    question: "چه زمانی جستجوی تقریب نزدیک‌ترین همسایه لازم نیست؟",
    language: "fa",
    kind: "factual",
    goldAnswer: "در مجموعهٔ زیر حدود ده هزار قطعه جستجوی دقیق معمولاً کافی است.",
    relevantDocIds: ["dense"],
  },
  {
    id: "q09",
    question: "Reciprocal Rank Fusion چرا امتیازهای خام را یک‌مقیاس نمی‌کند؟",
    language: "fa",
    kind: "factual",
    goldAnswer: "فقط از رتبه استفاده می‌کند؛ امتیاز ۱ روی کا به‌علاوه رتبه است.",
    relevantDocIds: ["hybrid"],
  },
  {
    id: "q10",
    question: "مقدار رایج k در RRF چقدر است؟",
    language: "fa",
    kind: "factual",
    goldAnswer: "معمولاً ۶۰.",
    relevantDocIds: ["hybrid"],
  },
  {
    id: "q11",
    question: "تفاوت faithfulness و answer correctness چیست؟",
    language: "fa",
    kind: "comparison",
    goldAnswer:
      "وفاداری پشتیبانی توسط زمینه است؛ درستی تطابق با واقعیت یا طلایی است. ممکن است وفادار ولی غلط باشد.",
    relevantDocIds: ["faithfulness"],
  },
  {
    id: "q12",
    question: "چرا پاسخ درست اما بی‌وفا در RAG محصولی خطرناک است؟",
    language: "fa",
    kind: "factual",
    goldAnswer: "استناد دروغین می‌سازد؛ جمله از دانش پارامتری آمده اما در قطعات نیست.",
    relevantDocIds: ["faithfulness", "citations"],
  },
  {
    id: "q13",
    question: "حداقل فیلدهای یک آیتم طلایی چیست؟",
    language: "fa",
    kind: "factual",
    goldAnswer: "سؤال، پاسخ کوتاه مرجع، و شناسهٔ اسناد مرتبط.",
    relevantDocIds: ["gold-set"],
  },
  {
    id: "q14",
    question: "چرا فقط سؤال‌های رونویسی‌شده از سند مجموعهٔ بدی می‌سازند؟",
    language: "fa",
    kind: "factual",
    goldAnswer: "بازیابی واژگانی به‌طور مصنوعی برنده می‌شود.",
    relevantDocIds: ["gold-set", "contamination"],
  },
  {
    id: "q15",
    question: "What is lost-in-the-middle in long-context RAG?",
    language: "en",
    kind: "factual",
    goldAnswer:
      "Models use evidence at the beginning or end of the context better than evidence buried in the middle.",
    relevantDocIds: ["lost-middle"],
  },
  {
    id: "q16",
    question: "آیا همیشه دادن ده قطعه بهتر از چهار قطعهٔ خوب است؟",
    language: "fa",
    kind: "factual",
    goldAnswer: "نه. قطعهٔ مرتبط ممکن است دفن شود و استفاده نشود.",
    relevantDocIds: ["lost-middle", "latency-cost"],
  },
  {
    id: "q17",
    question: "استناد تزئینی به قطعهٔ نامربوط چرا بد است؟",
    language: "fa",
    kind: "factual",
    goldAnswer: "اعتماد کاذب می‌سازد و از نداشتن استناد بدتر است.",
    relevantDocIds: ["citations"],
  },
  {
    id: "q18",
    question: "اگر هیچ قطعه‌ای از آستانه رد نشد پاسخ درست چیست؟",
    language: "fa",
    kind: "procedure",
    goldAnswer: "امتناع از پاسخ، نه یک مقدمهٔ بی‌منبع.",
    relevantDocIds: ["citations", "abstention"],
  },
  {
    id: "q19",
    question: "کدام صدک‌های تأخیر باید گزارش شوند؟",
    language: "fa",
    kind: "factual",
    goldAnswer: "p50 و p95 مهم‌تر از میانگین‌اند.",
    relevantDocIds: ["latency-cost"],
  },
  {
    id: "q20",
    question: "سه زمان جدا در RAG کدام‌اند؟",
    language: "fa",
    kind: "factual",
    goldAnswer: "بازیابی، تولید، و انتهابه‌انتها.",
    relevantDocIds: ["latency-cost"],
  },
  {
    id: "q21",
    question: "توهم بازیابی را با چه چیزی باید درمان کرد؟",
    language: "fa",
    kind: "factual",
    goldAnswer: "retriever بهتر، نه فقط محدود کردن تولید.",
    relevantDocIds: ["hallucination"],
  },
  {
    id: "q22",
    question: "بهترین آشکارساز توهم زمینه‌ای چیست؟",
    language: "fa",
    kind: "factual",
    goldAnswer: "سؤال‌های غیرقابل‌پاسخ یا خارج از دامنه.",
    relevantDocIds: ["hallucination", "abstention", "gold-set"],
  },
  {
    id: "q23",
    question: "الگوی رایج rerank چیست؟",
    language: "fa",
    kind: "procedure",
    goldAnswer: "retriever ارزان فهرست بلند می‌آورد و cross-encoder فهرست کوتاه را به مولد می‌دهد.",
    relevantDocIds: ["rerank"],
  },
  {
    id: "q24",
    question: "Recall@k دقیقاً چه چیزی را می‌سنجد؟",
    language: "fa",
    kind: "factual",
    goldAnswer: "سهم اسناد مرتبط که در k نتیجهٔ اول آمده‌اند.",
    relevantDocIds: ["ir-metrics"],
  },
  {
    id: "q25",
    question: "اگر اولین سند مرتبط رتبهٔ ۴ باشد MRR چقدر است؟",
    language: "fa",
    kind: "factual",
    goldAnswer: "۰.۲۵",
    relevantDocIds: ["ir-metrics"],
  },
  {
    id: "q26",
    question: "چرا متریک بازیابی به‌تنهایی برای RAG کافی نیست؟",
    language: "fa",
    kind: "factual",
    goldAnswer: "بازیابی عالی با مولد بی‌انضباط هنوز پاسخ بد می‌سازد.",
    relevantDocIds: ["ir-metrics", "failures"],
  },
  {
    id: "q27",
    question: "نشت اسپلیت در ارزیابی RAG یعنی چه؟",
    language: "fa",
    kind: "factual",
    goldAnswer: "پاسخ طلایی و سؤال تقریباً همان جملهٔ سند هستند و موفقیت کاذب می‌سازند.",
    relevantDocIds: ["failures", "contamination"],
  },
  {
    id: "q28",
    question: "دستور RAG نباید چه چیزی بگوید؟",
    language: "fa",
    kind: "factual",
    goldAnswer: "تا جایی که می‌دانی کمک کن یا اگر مطمئن نیستی حدس بزن.",
    relevantDocIds: ["prompting"],
  },
  {
    id: "q29",
    question: "ترتیب پیشنهادی بخش‌های prompt چیست؟",
    language: "fa",
    kind: "procedure",
    goldAnswer: "نقش، قوانین، قطعات شماره‌دار، سپس سؤال.",
    relevantDocIds: ["prompting"],
  },
  {
    id: "q30",
    question: "نرمال‌سازی ی و ک در فارسی چرا برای BM25 مهم است؟",
    language: "fa",
    kind: "factual",
    goldAnswer: "بدون آن تطبیق واژگانی بین نمایه و سؤال می‌شکند.",
    relevantDocIds: ["persian-tok", "bm25"],
  },
  {
    id: "q31",
    question: "باید توکنایز سؤال و سند یکی باشد یا جدا؟",
    language: "fa",
    kind: "factual",
    goldAnswer: "باید یک تابع باشد وگرنه دو سیستم جدا مقایسه می‌شوند.",
    relevantDocIds: ["persian-tok"],
  },
  {
    id: "q32",
    question: "آستانهٔ امتناع را می‌توان روی چه سیگنالی گذاشت؟",
    language: "fa",
    kind: "factual",
    goldAnswer: "امتیاز retriever یا همپوشانی واژه بین سؤال و قطعه.",
    relevantDocIds: ["abstention"],
  },
  {
    id: "q33",
    question: "دو متریک اصلی امتناع کدام‌اند؟",
    language: "fa",
    kind: "comparison",
    goldAnswer: "دقت امتناع روی غیرقابل‌پاسخ‌ها و پوشش پاسخ روی قابل‌پاسخ‌ها.",
    relevantDocIds: ["abstention"],
  },
  {
    id: "q34",
    question: "چرا تنظیم k روی همان سؤال‌های گزارش نهایی غلط است؟",
    language: "fa",
    kind: "factual",
    goldAnswer: "باید holdout جدا داشت؛ وگرنه عدد نهایی بیش‌برازش است.",
    relevantDocIds: ["contamination"],
  },
  {
    id: "q35",
    question: "فرادادهٔ حداقل نمایه چیست؟",
    language: "fa",
    kind: "factual",
    goldAnswer: "شناسهٔ سند، عنوان، شمارهٔ قطعه، تعداد توکن، و منبع.",
    relevantDocIds: ["indexing"],
  },
  {
    id: "q36",
    question: "چرا نمایه در حافظه برای این آزمایشگاه مناسب است؟",
    language: "fa",
    kind: "factual",
    goldAnswer: "هر اجرا تکرارپذیر است و به سرویس خارجی وابسته نیست.",
    relevantDocIds: ["indexing"],
  },
  {
    id: "q37",
    question: "How does hybrid retrieval usually help?",
    language: "en",
    kind: "factual",
    goldAnswer:
      "It helps when questions mix keyword-heavy and paraphrased information needs.",
    relevantDocIds: ["hybrid"],
  },
  {
    id: "q38",
    question: "قطعه‌بندی معنایی معمولاً برای چه اسنادی بهتر است؟",
    language: "fa",
    kind: "factual",
    goldAnswer: "مستندات فنی که یک واحد معنا باید کامل بماند.",
    relevantDocIds: ["chunking"],
  },
  {
    id: "q39",
    question: "اگر reranker روی دامنهٔ عمومی آموزش دیده باشد چه باید کرد؟",
    language: "fa",
    kind: "procedure",
    goldAnswer: "قبل و بعد آن را روی مجموعهٔ طلایی خودت مقایسه کن.",
    relevantDocIds: ["rerank"],
  },
  {
    id: "q40",
    question: "Hit rate در بازیابی یعنی چه؟",
    language: "fa",
    kind: "factual",
    goldAnswer: "اگر حداقل یک سند مرتبط در k باشد برابر ۱ است.",
    relevantDocIds: ["ir-metrics"],
  },
  {
    id: "q41",
    question: "قیمت سهام اپل در سال ۲۰۱۹ چقدر بود؟",
    language: "fa",
    kind: "unanswerable",
    goldAnswer: "در منابع نیست؛ باید امتناع شود.",
    relevantDocIds: [],
  },
  {
    id: "q42",
    question: "Who won the 2018 FIFA World Cup?",
    language: "en",
    kind: "unanswerable",
    goldAnswer: "Not in the corpus; the system should abstain.",
    relevantDocIds: [],
  },
  {
    id: "q43",
    question: "معماری دقیق GPT-4 چند لایه دارد؟",
    language: "fa",
    kind: "unanswerable",
    goldAnswer: "در این پیکره نیست.",
    relevantDocIds: [],
  },
  {
    id: "q44",
    question: "کدام داروی فشار خون برای بارداری توصیه می‌شود؟",
    language: "fa",
    kind: "unanswerable",
    goldAnswer: "خارج از دامنه؛ امتناع.",
    relevantDocIds: [],
  },
  {
    id: "q45",
    question: "How many parameters does Llama 3 70B actually have including embeddings?",
    language: "en",
    kind: "unanswerable",
    goldAnswer: "Not in corpus.",
    relevantDocIds: [],
  },
  {
    id: "q46",
    question: "آدرس دفتر مرکزی شرکت فرضی نورا در تهران چیست؟",
    language: "fa",
    kind: "unanswerable",
    goldAnswer: "در منابع بازیابی‌شده نیست.",
    relevantDocIds: [],
  },
  {
    id: "q47",
    question: "What temperature should I use to fine-tune a 70B model on one GPU in this lab?",
    language: "en",
    kind: "unanswerable",
    goldAnswer: "Not specified in the knowledge base.",
    relevantDocIds: [],
  },
  {
    id: "q48",
    question: "نتیجهٔ آزمایش بالینی دارو در سند شماره ۷۷ چه بود؟",
    language: "fa",
    kind: "unanswerable",
    goldAnswer: "چنین سندی در پیکره نیست.",
    relevantDocIds: [],
  },
];
